### ISSUE TITLE
Stopped working if no internet connection

### ISSUE THREAD

**Issue by smartswitchsio** [dhan-oss/DhanHQ-js#5]
If no internet connection while requesting it was stopped working suppose to give error message

![image](https://github.com/dhan-oss/DhanHQ-js/assets/41912495/b25e2d7e-3fd5-467e-a813-8bcc4f3bdce9)

**Comment by vinay-sd17** [comment]
Hi @smartswitchsio This is the expected behavior. You can catch "getaddrinfo" "enotfound" error & handle the behavior in the catch block to prevent your app from stopping when the internet connection is down.
