### ISSUE TITLE
Needed some more documentation for API real time data and info.

### ISSUE THREAD

**Issue by vishwamartur** [dhan-oss/DhanHQ-js#6]
Need F&O index live data and options price chart strike prince Realtime data need through API if it is configured with WebSocket it really help full.

**Comment by dhan-oss** [comment]
Hello @vishwamartur 

We have added Live Market Feed on Python library, yet to add on JS library as well. Since this is a community contributed script, you can add the same if you can or anyone else can contribute and raise a PR.
