### ISSUE TITLE
The package is not resolving with nextjs

### ISSUE THREAD

**Issue by phpmaster22** [dhan-oss/DhanHQ-js#8]
Hello, I am getting errors while using with NextJs application.

Cannot find module 'dhanhq' or its corresponding type declarations.ts(2307)

**Comment by phpmaster22** [comment]
@vinay-sd17 Please look into this issue. It works fine with normal nodejs.

**Comment by vinay-sd17** [comment]
@phpmaster22 It is fixed and published. Use version [1.0.4.](https://www.npmjs.com/package/dhanhq/v/1.0.4)
